services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: moodlyn-app
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            # Mount only specific directories to avoid overwriting the database
            - ./storage:/var/www/html/storage
            - ./bootstrap/cache:/var/www/html/bootstrap/cache
            # Create a named volume for the database to persist data
            - database_data:/var/www/html/database
        environment:
            - APP_NAME=Moodlyn
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_URL=http://localhost:80
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
            - SESSION_DRIVER=database
            - SESSION_LIFETIME=2880
            - SESSION_EXPIRE_ON_CLOSE=false
            - SESSION_SECURE_COOKIE=false
            - SESSION_SAME_SITE=lax
            - SESSION_DOMAIN=localhost:80
        networks:
            - moodlyn-network

volumes:
    database_data:
        driver: local

networks:
    moodlyn-network:
        driver: bridge
